---
- name: 'Ensure packages'
  package:
    name:
      - 'strongswan'
      - 'libcharon-extra-plugins'
    state: 'present'

- name: 'Ensure base config files'
  copy:
    src: "{{ file }}"
    dest: "/etc/{{ file }}"
    force: false
    mode: 0600
    owner: 'root'
    group: 'root'
  loop:
    - 'ipsec.conf'
    - 'ipsec.secrets'
  loop_control:
    loop_var: 'file'

- name: 'Ensure service'
  service:
    name: 'strongswan'
    state: 'started'
    enabled: true

- name: 'Add credentials to /etc/ipsec.secrets'
  blockinfile:
    path: '/etc/ipsec.secrets'
    block: "{{ conn.auth }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ conn.name }}"
  loop: "{{ ipsec_conns | default([]) }}"
  loop_control:
    loop_var: 'conn'

- name: 'Add server config to /etc/ipsec.conf'
  blockinfile:
    path: '/etc/ipsec.conf'
    block: |
      conn {{ conn.name }}
        authby=secret
        left={{ conn.pubip }}
        leftsubnet={{ conn.localsubnet }}
        right={{ conn.server }}
        rightsubnet={{ conn.subnet }}
        ike=aes256-sha1-modp1536
        esp=aes256-sha1-modp1536
        keyingtries=0
        ikelifetime=24h
        lifetime=1h
        dpddelay=30
        dpdtimeout=120
        dpdaction=restart
        auto=start
        leftauth=psk
        rightauth=psk
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ conn.name }}"
  loop: "{{ ipsec_conns | default([]) }}"
  loop_control:
    loop_var: 'conn'
  notify: 'restart strongswan'
